name: Maven Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy (-SNAPSHOT appended)"
        required: true
        default: "X.Y.Z"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Configure Git user
      run: |
        git config user.email "wdeploy@webdrone.com"
        git config user.name "wdeploy"
        git config user.username "wdeploy"
        git config user.password "${{ github.token }}"

    - name: Maven release
      run: mvn release:prepare release:perform -B -e -U -s $GITHUB_WORKSPACE/settings.xml --file pom.xml -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}-SNAPSHOT -DautoVersionSubmodules=true -Dtag=${{ github.event.inputs.releaseVersion }} -DreleaseOption="-DskipTests=true -Dmaven.javadoc.skip=true" -Dresume=false -Dmaven.site.skip=true -DgenerateReports=false -Dmaven.javadoc.skip=true -DconnectionUrl=https://${{github.token}}@github.com/meveo-org/meveo.git
      env:
        GITHUB_TOKEN: ${{ github.token }}